### ISSUE TITLE
How to disable close modal-sheet

### ISSUE THREAD

**Issue by giangjcr** [Temzasse/react-modal-sheet#51] opened 2021-10-07 04:00 UTC
Hello friends
how to make my **modal-sheet** always be displayed on screen as 100px drag max 500px and can't close modal-sheet when height is 100px

**Comment by guilnorth** [comment] 2021-11-12 22:32
> Same problem here. If you do the following, you still can close the sheet if you drag fast. `isOpen={true} onClose={()=>{}}`

Try this workaround https://github.com/Temzasse/react-modal-sheet/issues/6#issuecomment-967702561

**Comment by Temzasse** [comment] 2022-01-23 19:44
Duplicate of #6

**Closed by Temzasse** 2022-01-23 19:44 UTC
