### ISSUE TITLE
Content goes out of Sheet on Safari

### ISSUE THREAD

**Issue by Frknadgzl** [Temzasse/react-modal-sheet#129] opened 2023-06-06 13:33 UTC
I noticed that on safari on IPhone the content goes over the sheet. Here's an example. 

https://github.com/Temzasse/react-modal-sheet/assets/68433170/47b22c7c-8642-448e-8db2-cb27fb3bc1b4

**Comment by OhWonJu** [comment] 2023-06-16 01:24
I have the same issue as well. When I drag the Sheet.Content after resizing the browser, both the Sheet.Container and Sheet.Content get transformed simultaneously. As a result, the content disappears off the screen.

**Comment by Temzasse** [comment] 2023-06-17 19:46
It would be awesome if you could provide a reproduction case in [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/) 🙏🏻 

I have not been able to reproduce this locally yet so it's very difficult to solve it...

**Comment by Temzasse** [comment] 2023-06-20 20:02
This seems to be a duplicate of https://github.com/Temzasse/react-modal-sheet/issues/118.

Let's continue discussion in that one.

**Closed by Temzasse** 2023-06-20 20:02 UTC
