### ISSUE TITLE
Re-rendering parent page on sheet close

### ISSUE THREAD

**Issue by FilipJurkovic** [Temzasse/react-modal-sheet#123] opened 2023-04-24 17:12 UTC
Hello everyone,
This package is giving me quite a headache with re-rendering my scrollable parent page when closing the modal sheet.
The problem is that when it closes the page re-scrolls from the top to the previous position. 
Has anyone encountered this issue before?

Edit: This only happens on IOS mobile devices on all browsers

https://user-images.githubusercontent.com/74533259/234068253-74411948-276f-4526-b7e0-996255c6bb32.MP4

**Comment by Temzasse** [comment] 2023-05-17 08:16
Hi 👋🏻 

Would it be possible to have reproduction case in [CodeSandbox](https://codesandbox.io/)? Do you have some automatic scrolling logic in the parent component?

It's quite difficult to debug what the problem is without a reproduction 🙂

**Comment by Temzasse** [comment] 2023-06-17 21:07
Closing due to missing a repro.

**Closed by Temzasse** 2023-06-17 21:07 UTC
