### ISSUE TITLE
Break tree shaking issue because of a "motion"

### ISSUE THREAD

**Issue by seojisoosoo** [Temzasse/react-modal-sheet#158] opened 2024-02-20 08:55 UTC
![image](https://github.com/Temzasse/react-modal-sheet/assets/76681519/6aacadaf-a6ac-45bb-a152-a05f7fbf81ad)

Hi,

I am currently using Storybook with the `<LazyMotion strict>` tag. However, I've encountered an issue. In LazyMotion strict mode, I'm required to use "m" instead of "motion." The problem is that the Sheet component of react-modal-sheet uses "motion."

How can I fix this?

Thank you.

**Comment by Temzasse** [comment] 2024-05-11 12:11
Hi @seojisoosoo 👋🏻 

Using `LazyMotion` is not currently supported by this library but if it's not much of a hassle I can try to add support for it. I haven't used `LazyMotion` myself so I'm not familiar how it exactly works with 3rd party libs that consume `framer-motion`.

**Comment by Temzasse** [comment] 2024-05-11 12:12
Closing this as duplicate of #137

**Closed by Temzasse** 2024-05-11 12:12 UTC

**Comment by seojisoosoo** [comment] 2024-05-12 05:48
I see.. Thank you so much!
