### ISSUE TITLE
`draggableAt` is Not Working

### ISSUE THREAD

**Issue by anliting** [Temzasse/react-modal-sheet#168] opened 2024-07-26 03:09 UTC
`draggableAt` of the following example does not work on my device:
https://github.com/Temzasse/react-modal-sheet/blob/HEAD/example/components/ScrollableSnapPoints.tsx
https://temzasse.github.io/react-modal-sheet/#/scrollable-snap-points

What I expected is that, when the content is scrolled to top, the sheet is draggable.

<img src="https://github.com/user-attachments/assets/2425669e-dd91-4850-885b-219bf6b8d411" width="400">

**Comment by shivaluma** [comment] 2024-10-08 18:32
did you manage to have a workaround ?

**Comment by anliting** [comment] 2024-10-09 07:20
> did you manage to have a workaround ?

No, I did not.

**Comment by carlos-ribeiro-zup** [comment] 2024-10-25 20:39
This is pretty annoying. The drag action is only working on web browser when no device view is applied.
Thinking of create a fork just to fix that problem and others already opened on pull requests.

**Comment by Temzasse** [comment] 2024-10-27 11:58
Hey everybody! 👋🏻 

Chiming in here: the draggability is not super reliable on non-touch devices and I recommend testing it with a iOS/Android simulator instead of in Chrome's mobile emulation mode.

@carlos-ribeiro-zup I'm very much open to PRs to improve the draggability/scrollability 😊

**Comment by carlos-ribeiro-zup** [comment] 2024-10-27 14:30
Thanks for replying @Temzasse. As the issues and PRs were opened too many days ago, I thought you've kind abandoned the lib. Glad it's not, cuz you did a really nice job here.

**Comment by Temzasse** [comment] 2024-10-27 14:58
Thanks @carlos-ribeiro-zup 👍🏻 

I haven't abandoned the lib but I'm definitely much more busy nowadays so it's hard to find time to work on open source stuff 😞 Every now and then I get an energy boost and try to tackle multiple issues at once 😄

**Comment by alexkates** [comment] 2024-11-13 14:57
Anyone working on a fix for this yet? just ran into it as well.

**Comment by carlos-ribeiro-zup** [comment] 2024-11-13 15:00
> Anyone working on a fix for this yet? just ran into it as well.

As @Temzasse have mentioned [here](https://github.com/Temzasse/react-modal-sheet/issues/168#issuecomment-2439984816).

This issue could be closed.

**Comment by alexkates** [comment] 2024-11-13 16:01
You're right. Confirming after testing https://temzasse.github.io/react-modal-sheet/#/scrollable-snap-points on my iPhone simulator that it works as intended. Thanks!

**Comment by Temzasse** [comment] 2024-12-27 11:50
Closing this as non-issue. If there are problems on Android that should be tracked in a separate issue.

**Closed by Temzasse** 2024-12-27 11:50 UTC
