### ISSUE TITLE
Modal content scrolling out of the container 

### ISSUE THREAD

**Issue by odafeaggreh** [Temzasse/react-modal-sheet#95] opened 2022-10-06 19:03 UTC
Hi guys, please I need some help. The content in the button sheet tems to scroll out of the sheet itself occasionally and I'm not sure why it's having this behavior. 
![Screenshot_20221006-200233_WhatsApp](https://user-images.githubusercontent.com/53455512/194397176-90c0a485-23d2-4f24-a8b2-614280b99517.jpg)

**Comment by Temzasse** [comment] 2022-10-07 07:14
Can you provide a reproduction example in CodeSandbox or some other place where it would be possible to see the bug happen?

**Comment by Temzasse** [comment] 2022-10-07 19:15
This seems like a duplicate of https://github.com/Temzasse/react-modal-sheet/issues/47 which should be now fixed in the version [1.6.2](https://github.com/Temzasse/react-modal-sheet/releases/tag/v1.6.2).

**Closed by Temzasse** 2022-10-07 19:15 UTC
