### ISSUE TITLE
modal sheet overrides all modals, even when it is a child element, cannot control z-index

### ISSUE THREAD

**Issue by diegosystem32** [Temzasse/react-modal-sheet#180] opened 2024-12-03 21:25 UTC
Hello, I'm using https://ionicframework.com/docs/api/popover
and the modal sheet, but it overlaps all the react ionic modals, I tried to use the css z-index to keep it below the modals, but it doesn't work, it also doesn't work in the case of the Reactjs ionic modal being a child of react-sheet, how can I control the z-index so that it doesn't overlap the other modals? If you can, please send an example with react ionic

here the modal is open, when I click to open the react ionic popover, the popover stays behind, just like any other modal:

1:
![Screenshot 2024-12-03 182225](https://github.com/user-attachments/assets/868efd50-f9c6-4d70-914f-7e63b4f9795f)

2 modal (popover) color picker behind:

![Screenshot 2024-12-03 182241](https://github.com/user-attachments/assets/2fa92e1e-385a-4b58-be3c-ce0e1e982d68)

**Comment by Temzasse** [comment] 2024-12-27 11:41
This has been fixed in [v4](https://github.com/Temzasse/react-modal-sheet/releases/tag/v4.0.0). If you pass `<Sheet style={{ zIndex: 123 }}` it will be used instead of a hard coded value.

> [!NOTE]
> The version 4 has breaking changes as it expects `motion` as peer dependency so you need to migrate to the new [Motion](https://motion.dev/) package that has replaced `framer-motion`.

**Closed by Temzasse** 2024-12-27 11:41 UTC

**Comment by diegosystem32** [comment] 2024-12-27 16:15
> framer
I updated react-modal-sheet to v4, installed motion, set the <Sheet style={{ zIndex: 0 }} property, even so the popOver from ionic react UI that has z-index: 2007, remains behind the modal sheet

![image](https://github.com/user-attachments/assets/75c58cca-027d-4deb-b57a-8dde50c3f1ff)

**Comment by Temzasse** [comment] 2024-12-28 17:39
Please note that a higher `zIndex` value doesn't always guarantee that an element is rendered on top another one with a lower value.

The `Sheet` is rendered at the end of the `body` element via [React portal](https://react.dev/reference/react-dom/createPortal) to ensure that it is on top of any app content.

I'm not familiar with how Ionic renders its popover component so if doesn't handle z-index [stacking context](https://web.dev/learn/css/z-index) correctly there is not much that `react-modal-sheet` can do to help. Usually these kind of UI component libraries render popovers/dialogs/modals outside the main app content (eg. at the end of the `body`) to get around these kind of z-index issues.

I quickly tested React Aria's [Popover](https://react-spectrum.adobe.com/react-aria/Popover.html) component to see how it worked inside the `Sheet` component and it seems to work correctly so unfortunately the problem is most likely in Ionic.

**Comment by diegosystem32** [comment] 2024-12-31 00:32
> Observe que um `zIndex`valor mais alto nem sempre garante que um elemento seja renderizado sobre outro com um valor mais baixo.
> 
> O `Sheet`é renderizado no final do `body`elemento por meio [do portal React](https://react.dev/reference/react-dom/createPortal) para garantir que ele esteja no topo de qualquer conteúdo do aplicativo.
> 
> Não estou familiarizado com a forma como o Ionic renderiza seu componente popover, então se ele não manipula [o contexto de empilhamento](https://web.dev/learn/css/z-index) z-index corretamente, não há muito que `react-modal-sheet`possa ser feito para ajudar. Normalmente, esse tipo de biblioteca de componentes de IU renderiza popovers/diálogos/modais fora do conteúdo principal do aplicativo (por exemplo, no final do `body`) para contornar esse tipo de problema de z-index.
> 
> Testei rapidamente o componente [Popover](https://react-spectrum.adobe.com/react-aria/Popover.html) do React Aria para ver como ele funcionava dentro do `Sheet`componente e parece funcionar corretamente, então infelizmente o problema provavelmente está no Ionic.

I really appreciate your help, it really seems to be an ionic problem, my project is using the UI and components of the Ionic framework for react, because I am using capacitor to export the project on different platforms, I chose to create a solution to my problem in the ionic modal sheet itself [](https://ionicframework.com/docs/api/modal#sheet-modal) where it did not have responsive content and only allowed scrolling when fully opened, so I created a component to allow scrolling at any breakpoint, your project already has this, but I will choose to continue in ionic until I see a solution to use both together, otherwise I would have to create the modals. Thank you very much!
